#:schema node_modules/wrangler/config-schema.json
name = "img"
main = "src/index.js"
compatibility_date = "2024-11-12"

#enable-workers-logs
[observability]
enabled = true

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"


[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]

